// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: src/protos/dataserver.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataNodeClient is the client API for DataNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeClient interface {
	WriteFile(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error)
	ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error)
	HearHeart(ctx context.Context, in *HeartRequest, opts ...grpc.CallOption) (*HeartResponse, error)
	LocalObject(ctx context.Context, in *LocalRequest, opts ...grpc.CallOption) (*LocalReply, error)
}

type dataNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeClient(cc grpc.ClientConnInterface) DataNodeClient {
	return &dataNodeClient{cc}
}

func (c *dataNodeClient) WriteFile(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error) {
	out := new(WriteReply)
	err := c.cc.Invoke(ctx, "/protos.DataNode/WriteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeClient) ReadFile(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error) {
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, "/protos.DataNode/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeClient) HearHeart(ctx context.Context, in *HeartRequest, opts ...grpc.CallOption) (*HeartResponse, error) {
	out := new(HeartResponse)
	err := c.cc.Invoke(ctx, "/protos.DataNode/HearHeart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNodeClient) LocalObject(ctx context.Context, in *LocalRequest, opts ...grpc.CallOption) (*LocalReply, error) {
	out := new(LocalReply)
	err := c.cc.Invoke(ctx, "/protos.DataNode/LocalObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeServer is the server API for DataNode service.
// All implementations must embed UnimplementedDataNodeServer
// for forward compatibility
type DataNodeServer interface {
	WriteFile(context.Context, *WriteRequest) (*WriteReply, error)
	ReadFile(context.Context, *ReadRequest) (*ReadReply, error)
	HearHeart(context.Context, *HeartRequest) (*HeartResponse, error)
	LocalObject(context.Context, *LocalRequest) (*LocalReply, error)
	mustEmbedUnimplementedDataNodeServer()
}

// UnimplementedDataNodeServer must be embedded to have forward compatible implementations.
type UnimplementedDataNodeServer struct {
}

func (UnimplementedDataNodeServer) WriteFile(context.Context, *WriteRequest) (*WriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedDataNodeServer) ReadFile(context.Context, *ReadRequest) (*ReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedDataNodeServer) HearHeart(context.Context, *HeartRequest) (*HeartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HearHeart not implemented")
}
func (UnimplementedDataNodeServer) LocalObject(context.Context, *LocalRequest) (*LocalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalObject not implemented")
}
func (UnimplementedDataNodeServer) mustEmbedUnimplementedDataNodeServer() {}

// UnsafeDataNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServer will
// result in compilation errors.
type UnsafeDataNodeServer interface {
	mustEmbedUnimplementedDataNodeServer()
}

func RegisterDataNodeServer(s grpc.ServiceRegistrar, srv DataNodeServer) {
	s.RegisterService(&DataNode_ServiceDesc, srv)
}

func _DataNode_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataNode/WriteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).WriteFile(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNode_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataNode/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).ReadFile(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNode_HearHeart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).HearHeart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataNode/HearHeart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).HearHeart(ctx, req.(*HeartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNode_LocalObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServer).LocalObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DataNode/LocalObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServer).LocalObject(ctx, req.(*LocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNode_ServiceDesc is the grpc.ServiceDesc for DataNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DataNode",
	HandlerType: (*DataNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteFile",
			Handler:    _DataNode_WriteFile_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _DataNode_ReadFile_Handler,
		},
		{
			MethodName: "HearHeart",
			Handler:    _DataNode_HearHeart_Handler,
		},
		{
			MethodName: "LocalObject",
			Handler:    _DataNode_LocalObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/protos/dataserver.proto",
}
